broadcast-exceptions: false
disable-tnt: false
enable-map-gui: false
enable-server-ping-records: false
show-damage-summary: false
lock-counter: 0
lock-duration: 5
lock-threshold: 5
lock-until: 0
password: ''
welcome-state: false
welcome-subtitle: ''
welcome-title: ''