name: ServerPlugin
main: com.amrsatrio.server.ServerPlugin
version: 1.0.0-1.14.3
authors:
  - Amrsatrio
  - ammar18
build-date: ${timestamp}
commands:
  backupserver:
    usage: /<command>
  colorguide:
    description: Displays all Minecraft formatting codes
    usage: /<command>
    aliases: colguide
  copyfile:
    usage: /<command>
  download:
    description: Download a file into the server folder
    usage: /<command> <url...>
    aliases: dl
  #  flyspeed:
  #    description: Show the fly speed GUI
  #    usage: /<command>
  #    aliases: fs
  getbanner:
    description: Open the banner generator GUI
    usage: /command
  inputphone:
    usage: /<command> <up|down|left|right>
  listfile:
    description: List files in folder in a GUI. If path is not defined, this server's folder will be opened.
    usage: /<command> [path]
    aliases: ls
  nameitem:
    description: Format the currently holding item's name
    usage: /<command> <name...>
  password:
    description: Change the password used to execute protected commands
    usage: /<command> <newPassword <confirmPassword>|clear>
  playerhist:
    description: Shows the player name history of a player
    usage: /<command> <player>
  pushcommand:
    description: push a console command through to McMyAdmin as the current user
    usage: /<command> <serverCommand>
  svping:
    description: check that the server is still responding
    usage: /<command> [arg0]
permissions:
  tb24serv.battleroyale:
    description: Allow user to interact with the battle royale system
    default: op